# sysprep; version 2020-04-27; strachotao 
#
# sysprep pro centos7+ a ubuntu 18.04
# provede:
#  - nastaveni sitove karty
#    pokud neni nastaveny newip, neprovede zmenu tcp/ip a pokracuje dal
#  - nastaveni hostname
#    pokud neni nastaveny newname, jmeno zustane a pokracuje dal
#  - smaze rsa klice (po bootu si ssh vygeneruje nove)
#  - nastavi barvu promptu roota (cervena=31 zelena=32 oranzova=33 modra=34 sediva=37)
#    pokud neni nastaveny promptcolor, preskoci a pokracuje dal
#  - reboot
#
# USAGE:
#  ansible-playbook -l se89 -e 'newip=192.168.0.83 newmask=255.255.255.0 newcidr=24 newgw=192.168.0.1 newdns1=192.168.0.1 newname=se92 promptcolor=37 reboot=true nicname=enp0s3' sysprep.yml

---
- become: yes
  hosts: all 
  gather_facts: True

  tasks:

  - name: remove current ifcfg
    file: path=/etc/sysconfig/network-scripts/ifcfg-{{ nicname }} state=absent
    when: newip is defined and ansible_os_family == "RedHat"

  - name: touch ifcfg
    file: path=/etc/sysconfig/network-scripts/ifcfg-{{ nicname }}  mode=0644 owner=root group=root state=touch
    when: newip is defined and ansible_os_family == "RedHat"

  - name: deploy ifcfg NIC
    blockinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-{{ nicname }}
      owner: root
      group: root
      mode: 0644
      block: |
        TYPE=Ethernet
        PROXY_METHOD=none
        BROWSER_ONLY=no
        BOOTPROTO=none
        IPADDR={{ newip }}
        NETMASK={{ newmask }}
        GATEWAY={{ newgw }}
        DNS1={{ newdns1 }}
        DEFROUTE=yes
        IPV4_FAILURE_FATAL=no
        NAME={{ nicname }}
        DEVICE={{ nicname }}
        ONBOOT=yes
    when: newip is defined and ansible_os_family == "RedHat"

  - name: remove current netplan
    file: path=/etc/netplan/01-netcfg.yaml state=absent
    when: newip is defined and ansible_os_family == 'Debian'

  - name: touch netplan
    file: path=/etc/netplan/01-netcfg.yaml mode=0644 owner=root group=root state=touch
    when: newip is defined and ansible_os_family == 'Debian'

  - name: deploy netplan
    blockinfile:
      path: /etc/netplan/01-netcfg.yaml
      block: |
        # netplan; version {{ lookup('pipe','date +%Y-%m-%d') }}; strachotao
        # This file describes the network interfaces available on your system
        # For more information, see netplan(5).
        network:
          version: 2
          renderer: networkd
          ethernets:
            enp0s3:
              addresses: [ {{ newip }}/{{ newcidr }} ]
              gateway4: {{ newgw }}
              nameservers:
                search: [ Debian ]
                addresses:
                    - "{{ newdns1 }}"
    when: newip is defined and ansible_os_family == 'Debian'

  - name: remove current hostname
    file: path=/etc/hostname state=absent
    when: newname is defined

  - name: touch hostname
    file: path=/etc/hostname mode=0644 owner=root group=root state=touch
    when: newname is defined

  - name: deploy hostname
    lineinfile:
      path: /etc/hostname
      line: "{{ newname }}"
    when: newname is defined

  - name: refresh ssh daemon
    shell: 'rm -v /etc/ssh/ssh_host_*'
    when: newip is defined and ansible_os_family == "RedHat"

  - name: set marker in prompt
    blockinfile:
      path: /root/.bash_profile
      block: |
        export PS1='\[\e[0;{{ promptcolor }}m\]\u@\h \W\[\e[m\] \$ '
    when: promptcolor is defined and ansible_os_family == "RedHat"

  - name: set marker in prompt
    blockinfile:
      path: /root/.profile
      block: |
        export PS1='\[\e[0;{{ promptcolor }}m\]\u@\h \W\[\e[m\] \$ '
    when: promptcolor is defined and ansible_os_family == "Debian"

  - name: send reboot
    command: init 6 
    when: reboot is defined
