#!/bin/bash
# ssh isReachable; version 2020-07-08; strachotao

#. $MUNIN_LIBDIR/plugins/plugin.sh

data="/etc/munin/ssh_is_reachable_data"

case $1 in
	config)
	echo "graph_title ssh dostupnost"
        echo 'graph_scale no'
        echo "graph_category ssh"
        echo 'graph_printf %3.0lf'
        echo "graph_info Dostupnost z brnv1s04 na server:tcp22 aka ssh; 0=OK 5=excluded 10=nedostupny; Plugin sbira data pomoci cronu /etc/munin/ssh_is_reachable.sh, v tomto skritpu lze excludovad konkretni servery, aby se nehlasily jako nedostupne"
        for server in $(cat $data); do
            server=$(awk -F\; '{print $1}' <<< ${server})
            echo "${server}.label ${server}"
            echo "${server}.warning 8"
            echo "${server}.critical 9"
        done
        exit 0
        ;;
esac

for server in $(cat $data); do
    serverName=$(awk -F\; '{print $1}' <<< ${server})
    value=$(awk -F\; '{print $2}' <<< ${server})
    echo "${serverName}.value $value"
done
